language: node_js
node_js:
  - "8"

cache:
  directories:
    - "src/node_modules"

git:
  depth: 3

branches:
  only:
    - pre_deploy

before_install:
  # update npm
  - npm update
  # move to /src
  - cd src
install:
  # install modules (using cache)
  - npm install
before_script:
  # write current build number
  - sed -i -e "s/BUILD_NUMBER/$TRAVIS_BUILD_NUMBER/" ./build_info.json
script:
  # start jest test
  - npm run test
  # coveralls
  - cat ./coverage/lcov.info | ./node_modules/.bin/coveralls
  # start build
  - npm run generate

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_ACCESS_TOKEN
  target-branch: master
  local-dir: src/dist
  on:
    branch: pre_deploy
