language: node_js
node_js:
  - "8"

cache:
  directories:
    - "node_modules"

git:
  depth: 3

branches:
  only:
  - pre_deploy

install:
  - cd src
  # write current build number
  - sed -i -e "s/BUILD_NUMBER/$TRAVIS_BUILD_NUMBER/" ./build_info.json
  - npm install
  - npm run generate

script:
  - echo "Skipping tests"

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_ACCESS_TOKEN
  target-branch: master
  local-dir: src/dist
  on:
    branch: pre_deploy