language: node_js
node_js:
  - "8"

cache:
  directories:
    - "src/node_modules"

git:
  depth: 3

branches:
  only:
  - pre_deploy

before_install:
  - npm update
install:
  - cd src
  - npm install
script:
  - npm run test --coverage && cat ./coverage/lcov.info | coveralls
  # write current build number
  - sed -i -e "s/BUILD_NUMBER/$TRAVIS_BUILD_NUMBER/" ./build_info.json
  # build
  - npm run generate

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_ACCESS_TOKEN
  target-branch: master
  local-dir: src/dist
  on:
    branch: pre_deploy